### ISSUE TITLE
Alternative Download

### ISSUE THREAD

**Issue by IzzySoft** [OmGodse/Notally#1]
Nice to see a tracker-free notes app! Would you consider to give "Google-less users" a chance to grab it – maybe by tagging your releases and attaching the APK to the corresponding tag? Thanks in advance!

**Comment by OmGodse** [comment]
Glad to hear you liked the app! "Google less users" can now download the app by grabbing it from the releases page

**Comment by IzzySoft** [comment]
Wow, that was fast – thanks a lot! Will you keep tagging future releases and attaching the APK to them? Then you could point other Google-less users [here](https://apt.izzysoft.de/fdroid/index/apk/com.omgodse.notally), where your app should show up tomorrow evening (in about 22h) with the next sync, and will be updated within 24h of your tagging and attaching the APK.

If you want to, I could also help you getting your app listed at [F-Droid](https://f-droid.org/), which would build the app from sources. F-Droid is the most trusted place for people favoring Android FOSS apps (mine is the second largest repo and accessible with their app; due to less strict inclusion criteria, I can offer apps which would not be accepted there, so my repo "expands" the "storeroom").

If you want to link to your app in my repo, there's [a badge available](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) you can use for that.

Thanks again!

**Comment by OmGodse** [comment]
Yes, I'll keep tagging future releases and attaching the APK to them. However, I do have one small request to make. Could you please amend the spelling of the word **richt-text** to **rich text** [here?](https://apt.izzysoft.de/fdroid/index/apk/com.omgodse.notally)

**Comment by IzzySoft** [comment]
Ouch – sure, done! With the next sync, which I most likely just missed by minutes…

If you want anything else updated, amended etc., just let me know!

**Comment by OmGodse** [comment]
Could you please update the images in your repo with the new ones I've added in the latest commit?

**Comment by IzzySoft** [comment]
Done (removed the framing again though, considering folks browsing from their smartphones), thanks for the hint! Will show up with the next sync.

Maybe you want to use [Fastlane structures](https://gitlab.com/snippets/1895688) for images, description etc? That would be especially helpful should you apply for listing with [F-Droid](https://f-droid.org/). As for my repo: my updater would automatically pick the per-release changelogs and show them along.

**Comment by OmGodse** [comment]
Oh you didn't need to remove the framing, that'll decrease the quality of the images. You can update the repository images with the original screenshots I've attached.

![Make Lists](https://user-images.githubusercontent.com/64728411/88251900-ecb50300-ccc9-11ea-80d0-4a1f3551c908.png)
![Notally](https://user-images.githubusercontent.com/64728411/88251901-ede63000-ccc9-11ea-945a-9d3570f11ca6.png)
![Take Notes](https://user-images.githubusercontent.com/64728411/88251902-ee7ec680-ccc9-11ea-8c27-3b69a48975be.png)
![Dark Mode](https://user-images.githubusercontent.com/64728411/88251903-ee7ec680-ccc9-11ea-9d7f-38bda5602cdb.png)

**Comment by IzzySoft** [comment]
Thanks! Replaced again. Btw: I always deframe (if framed and size permits – no use if width already is below 300px) and downsize (if width > 350px). Primary reason for screenshots is giving an idea about the app – not being an art gallery :wink:

**Comment by OmGodse** [comment]
I disagree. 
As a developer who's spent a lot of time on making the app simple and elegant (and the screenshots too), it's misrepresentative to downsize the quality of images to display them to the consumers.

So could you include the images in the original quality in the repo? 
Also, the correct order of the images is :

1. Notally
2. Take Notes
3. Make Lists
4. Dark Mode

**Comment by IzzySoft** [comment]
Sorry, but no. If someone wants to see the full size images, they are part of your representation here. Representation in my repo is just a preview. The max size of 350px for the smallest side of the image is used for all screenshots of all apps there.

Order is arranged alpha-numerical. I've just renamed the files according to your preference, so they should now be displayed in that order after the next sync.

**Comment by OmGodse** [comment]
I’m sorry but that’s not acceptable. I would like the users (potential) to see the screenshots in the quality in which they were intended to be seen. Part of the reason many perfectly good open source and free software have not become mainstream is that they’ve neglected the UI in favour of cramming functionality. (Notably is the exception of course ) And as the images in your repository might be many people’s first impression of the app, it’s important that they look beautiful.

**Comment by IzzySoft** [comment]
I of course respect your wishes as the author – and hope you also respect mine as the repo owner. So if you cannot accept the resized screenshots, and I cannot accept them full-size: Do you want me to remove the screenshots then?

**Comment by OmGodse** [comment]
Well no, that's throwing the baby out with the bath water. However what's the reason for not including high resolution images in the repository page?

**Comment by IzzySoft** [comment]
> Well no, that's throwing the baby out with the bath water.

Indeed :grin:

> what's the reason for not including high resolution images in the repository page?

As pointed out:

* size. The repo runs on my personal space. With 500+ apps (at the time of this writing: 542), this would sum up a lot, and in most cases size of the images would exceed size of the app itself (for some it would even have been by factor 10).
* respect to user's data plan. I don't want to burn their plans with "oversized" images. Users shall feel safe from that when visiting my repo – be it with the browser, or the F-Droid app (images are the same in both). Images are displayed by default, so they cannot choose. They can however choose following a link to a "high-res gallery" (so if you have any, I could add a link to that in the app description).¹
* no need for images bigger than the screen :wink:

Take a look at screenshot resolutions at GPlay or Appbrain. They usually resize to less than 300px for the shorter side (288px at both; even worse, if you click an image in GPlay you *seem* to get something bigger, but that's just "upscaled"). I at least leave that at 350px as a compromise.

----

¹ Before you ask: no, the structure of an F-Droid repo does not have a place for "thumbnails". Screenshots are always delivered "full size". So no option to work around that this way.

**Comment by OmGodse** [comment]
If the first point is really an issue, you need not host images yourself, you can simply embed them in your website. They'll always be stored in the `images` folder of the master branch. As for the data plan, an additional `MB` here and there wouldn't cause them too much pain.

Google Play seems to scale down images when on a low spec device, however they display them close to the original quality when you visit them from a high spec device.

However if for some reason you can't utilize these alternatives, then this would be greatly appreciated.
> I can add a pointer to that to the app description, mentioning how much you value the design and wish the potential user having the right "first impression"

BTW do you track downloads of apps in your repository?

**Comment by IzzySoft** [comment]
> you need not host images yourself, you can simply embed them in your website

now guess on what space that might run :rofl: Apart from that, this wouldn't work with the repo. Screenshots must be in a specific structure to be recognized. That's why I suggested to link to your gallery.

> As for the data plan, an additional MB here and there wouldn't cause them too much pain.

How can you tell? It's not just the "privileged western-world kids". In some areas that's *really* expensive.

> Google Play seems to scale down images when on a low spec device, however they display them close to the original quality when you visit them from a high spec device.

Funny. That means my monitor is too small as they serve me those 288px screenshots when visiting their website? OK, 19" is not the biggest one…

So as pointed out multiple times now: If you host those high-res image on your website, just tell me a link and I include it with the description.

> BTW do you track downloads of apps in your repository?

Nope, no tracking here. Not even a download counter, sorry.

**Comment by OmGodse** [comment]
Why do you not have a download counter? That can't possibly hurt user privacy by any measure.

Also,  I'm interested in getting my app listed at FDroid (I looked around and they seem to support high res screenshots, plus there's a lack of elegant apps there)

**Comment by IzzySoft** [comment]
> Why do you not have a download counter?

1. because nobody implemented it into fdroidserver
2. because even if, it wouldn't be very useful – or quite overkill, keeping it sync'd across multiple servers/mirrors etc

So before you ask: no, at least in the foreseeable future there won't be any.

> I'm interested in getting my app listed at FDroid

You could start by opening an [RFP](https://gitlab.com/fdroid/rfp/issues) (Request For Packaging).

**Comment by OmGodse** [comment]
I looked at the inclusion policy of FDroid and it seems like they build apps from the source. Does that mean I'll have to hand over the APK signing key to them when I submit my application?

**Comment by IzzySoft** [comment]
Nope. They sign with their own keys (creating one for each app). If you wanna go "advanced", there're "reproducible builds" (where the unsigned APK built by F-Droid 100% corresponds to the unsigned one you've build, to put it into simple terms) – if those match, F-Droid'd take the one signed by you and add their own signature on top, so cross-updates are possible (otherwise they're not).

**Comment by OmGodse** [comment]
I think I'll keep my app in your repository for the time being. I'm planning on integrating a bit of Google Play Services (The billing part) into my app soon. I'll attach 2 APK's to the releases at that point with one being the clean one and the other with the billing integrated. Do you think your repository could handle that?

**Comment by OmGodse** [comment]
And could we continue this conversation over email from now?

**Comment by IzzySoft** [comment]
> Do you think your repository could handle that?

Sure. Just let me know *before* you make that release and tell me your naming conventions for the files. If eg the G-one always has *`google*` in its name, I can exclude it. If the FOSS one has `*foss*`, I can stick to that. If both, I can both for double-safety :grin:

> And could we continue this conversation over email from now?

You know where to find my address I guess :wink:

**Comment by OmGodse** [comment]
I really don't. 😂

You can however contact me [here](omgodseapps@gmail.com)

If I switch to the fastlane data structure for descriptions and other assets, will your repository automatically pull it and display it on the landing page?

**Comment by IzzySoft** [comment]
Houston, you have a problem: addresses from that domain are "refused" by my mail server. They will reach me, but you will receive only an auto-reply telling you to please use an address not hosted at one of the big data collectors…

And as you don't: at least in Germany, websites need to have an imprint, where you can find contact information. For repo/development stuff I use (my Github nick) "at" qumran "dot" org.

As for Fastlane: No, it doesn't get picked up automatically. I first need to set it up for your app, then the per-release changelogs are pulled automatically. All else is manual, as some devs have too big files, framed screenshots etc. which need (manual) adjustment…

**Comment by OmGodse** [comment]
Oh, well I guess that'll take you some time. Till then can you just update the bulleted points on your repo's page with the ones from the [README.md](https://github.com/OmGodse/Notally/blob/master/README.md) and replace the Take Notes screenshot with this (I've added links in the latest update
![Take Notes](https://user-images.githubusercontent.com/64728411/92692624-100f3c80-f362-11ea-8557-cd90b3ddc34f.png))

**Comment by IzzySoft** [comment]
> I guess that'll take you some time

Haha… you're optimistic. The image part probably won't be automated in my repo – at least not for the candidates mentioned. Description/summary maybe. But first you must provide fastlane, or I cannot pick it up anyhow.

Your other wishes "have been granted" (bullet-points & screenshot updated), will become visible tomorrow with the next regular sync.

**Comment by OmGodse** [comment]
As I understand you'll adjust the screenshots manually, which leaves the following fields. Could you clarify which of these you'll pick up with fastlane ?

1. Short description
1. Long description
1. Title
1. Icon
1. Changelog

You've mentioned before that hosting high resolution images is difficult for you. If I include them in the repository itself as losslessly compressed JPEG's would you consider that an acceptable compromise?

**Comment by IzzySoft** [comment]
OK, let me sum it up again:

* after initially having configured fastlane for an app in metadata here, only the per-release changelogs will be picked up automatically (provided their name matches the versionCode of the APK picked from `releases/`). I had no time yet to set up anything else from fastlane yet.
* in the (foreseeable) future, I *might* set up picking shortdesc as well – or short+full based on (per-app) configuration. Background on fulldesc: if not properly formatted (and often they are not), the result would be a mess (a single huge block/paragraph) – or I'd need to somehow distinguish between "properly formatted" (take as-is) and "just plain ASCII" (which would need formatting to be set up). That would take time.
* I *could* probably pick the icon as well – as all I'd have to do for that is to resize it to 48x48 (else again it would mess up things). I could also pickup the featureGraphic maybe.
* screenshots: same thing as with fulldesc. Not only I'd need to resize them properly – but I'd also need to distinguish between "framed" ones I'd need to "unframe" first, which cannot be done automatically.

And I won't discuss it again: screenshots in my repo will be resized to max 350 at their small side, and will be lossy-compressed to 75% JPG (unless they are already at around 20k without that). I can include a link to a full-res image gallery with the app description, though. Please accept that I won't discuss this part again.

**Comment by OmGodse** [comment]
I think you can remove the app from your repository now that it's on FDroid. Thanks for hosting it until now :)

**Comment by IzzySoft** [comment]
Thanks, marked for removal! I usually give it a few days overlap for the users to notice. Will remove it in about a week.

**Comment by OmGodse** [comment]
Hi, so it's been 5 days since I've released an update. Do you know when it will be picked up by Fdroid? I checked the metadata file and it contains the v3.3 (Current) release but the latest release on the website and the client is 3.2.
