### ISSUE TITLE
[Feature Request] Better notes editing

### ISSUE THREAD

**Issue by primarto** [OmGodse/Notally#10]
For better and easier editing notes **double tap** anywhere, see photo (like notepad from braden farmer)

![f12c49e0-3539-474c-9492-e1e529d61da1](https://user-images.githubusercontent.com/62907157/82384844-11260200-9a31-11ea-9b31-155a689a0d84.jpg)

**Comment by praveenrajput** [comment]
@primarto I'm quite not getting what you are trying to say?

**Comment by primarto** [comment]
View mode for notes and for edit notes double tap anywhere

**Comment by OmGodse** [comment]
That is intentional. We can't reserve the entire screen for displaying a note because the labels go directly underneath the text.
