### ISSUE TITLE
Details for notes

### ISSUE THREAD

**Issue by primarto** [OmGodse/Notally#13]
When long press on some notes, a category window opens and here is good to add "Details".

"Details" - Fisrt time and date when note is created, last time and date when note is modified, number of characters and other things if you think they are needed. (like unote)

![75e18372-4251-4592-83c4-1e6f3433d33d](https://user-images.githubusercontent.com/62907157/82386826-b216bc00-9a35-11ea-8100-066b32c882a7.jpg)

**Comment by sojusnik** [comment]
Like this idea a lot!

This would also declutter the area under the title of a note when in edit view, by removing the creation date from there.
The following entries could be added into "Details":

Created: date + time
Modified: date + time
Words: number
Characters: number
Characters (without space): number

This "Details" section should also be accessible under the 3 vertical dots menu in the toolbar. BTW, "Export" is missing there too.

**Comment by OmGodse** [comment]
There's been a pull request related to this. I've decided not to include a details section as it would mostly be a frivolous feature.
