### ISSUE TITLE
Looking for someone to create an icon that reflects the theme of the app

### ISSUE THREAD

**Issue by OmGodse** [OmGodse/Notally#16]
If you would like to help, please contact me [here](mailto:omgodseapps@gmail.com)

**Comment by praveenrajput** [comment]
What kind of icon you have in mind?

**Comment by OmGodse** [comment]
I'm going to create a few more apps in the future, so it should have a consistent style that can be adapted to other apps too but at the same time each icon should be unique.

Kind of like the icons used by Play Books, Play Music, Play Movies, etc

**Comment by primarto** [comment]
Something like "simple app" or "essential app" icon maybe a little more modern

**Comment by OmGodse** [comment]
Exactly, something like that.
