### ISSUE TITLE
App crashes when trying to delete an empty note

### ISSUE THREAD

**Issue by kshitij86** [OmGodse/Notally#2]

**Comment by OmGodse** [comment]
I'm sorry but could you be a bit more precise?

**Comment by kshitij86** [comment]
When you open an empty note and attempt to delete it using the delete option on the top right, before writing anything in it, the app crashes.

**Comment by OmGodse** [comment]
Thanks for pointing out the bug. I've fixed it in the latest commit and it should soon roll out on the Play Store.
