### ISSUE TITLE
Unable to create a pull request 

### ISSUE THREAD

**Issue by praveenrajput** [OmGodse/Notally#21]
I'm not able to create a pull request , on creating a pull request from Android Studio, It's giving following error

**Can't Create Pull Request
Push failed:
remote: Permission to OmGodse/Notally.git denied to praveenrajput.
unable to access 'https://github.com/OmGodse/Notally.git/': The requested URL returned error: 403**

**Comment by OmGodse** [comment]
You'll need to first fork the repository before creating a pull request. [For more information you can check out this link](https://opensource.com/article/19/7/create-pull-request-github)
