### ISSUE TITLE
promote notally

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [OmGodse/Notally#25]
i looking at fdroid and reposorities and so i see the Nozally on Fdroid on [Izzy his Repo](https://apt.izzysoft.de/fdroid/index/apk/com.omgodse.notally)

i paint the logo(s) as a acrylicic picture and promote it on [mastodon](https://mastodon.technology/@mondstern/104562566847296757) and [pixelfed.social](https://pixelfed.social/p/mondstern/191852899746320384)
I hope you're happy about this.

**Comment by OmGodse** [comment]
Yes. That's very helpful
