### ISSUE TITLE
Possibility of Supporting Android 5.x

### ISSUE THREAD

**Issue by moriel5** [OmGodse/Notally#27]
I'm not sure how much of a drawback there would be from doing this, however could you please add support for APIs 21-22, or a least just API 22 (5.1)?

We have two tablets at home (Amazon Kindle HD 10 2017 running LOS12.1 (LOS14.1 is not stable enough to be a daily driver), and a HiSense Sero 7 Pro, running AOSP 6.0.1, however will be downgraded to LOS12.1 due to instabilities regarding the package manager), and it would be great to be able to run Notally on both of them.

**Comment by OmGodse** [comment]
I looked into it and it doesn't seem too hard to support Android 5.0 and later. There would only be around 4 to 5 changes required (as we're not taking any particular advantage of the system features introduced in the later versions).

However one thing will definitely change i.e the status bar being white in the light theme. (As that was introduced in API 21 i.e Marshmallow)

**Comment by moriel5** [comment]
That is perfectly fine.
The most important thing is the featureset at this weight, and since this does not impact the main part of the GUI (though personally, I'm not really a fan of most of the changes brought about by Material Design 2, I think the original Material Design was better (though there are a few things I like from the newer revision)).

**Comment by OmGodse** [comment]
I'm linking to an [APK](https://drive.google.com/file/d/1YnzWY1vKyC836Op8onFNEiptXsY0dInK/view?usp=sharing) that is compatible with Lollipop. I've only tested it yet on an emulator. Could you check it out and ensure it works well on an actual physical device? (And include some screenshots too)

**Comment by moriel5** [comment]
Thanks, I'll test this out a soon as possible.
If I won't have time today, I'll do so on Sunday.

**Comment by moriel5** [comment]
Sorry about being late, I'm currently about to upload the pictures (just need to organize them).
I had encountered no bugs pertaining the additional API support. On the contrary, Notally worked flawlessly (aside from a small bug pertaining landscape mode, which affects previous versions on Android 6+) on my mother's tablet.

**Comment by OmGodse** [comment]
What's the bug?

**Comment by moriel5** [comment]
When attempting to open a menu, the bottom option is obscured (mainly relevant when there are only two options).
However, I already have a suggestion how to fix this, which I shall post in a separate issue (I need to copy a screenshot from another app, that influences this suggestion, over from my phone first).

**Comment by OmGodse** [comment]
I don't think that's a bug. To access the bottom option, all you have to do is swipe up a bit.

**Comment by moriel5** [comment]
Here are the pictures.
I had only taken screenshots in landscape, however there are no differences between Lollypop and newer versions in regards to the GUI (aside from the navbar color, of course).

It is an archive due to the amount of screenshots, so that you could decide which are worthwhile.
It refused to upload a 7z archive, so here is a zip archive.

[Screenshot_2020-08-08-23-.zip](https://github.com/OmGodse/Notally/files/5048801/Screenshot_2020-08-08-23-.zip)

**Comment by moriel5** [comment]
> I don't think that's a bug. To access the bottom option, all you have to do is swipe up a bit.

The bug is that id does not show all options, which is why it is only truly relevant for when there are only two options.

**Comment by OmGodse** [comment]
Released the APK with the bug fix. You can either wait for it to roll out on the Play Store or install it from [here](https://github.com/OmGodse/Notally/releases/tag/v2.8)

**Comment by moriel5** [comment]
Thanks, that's awesome.
