### ISSUE TITLE
Please  add clickable links in notes.

### ISSUE THREAD

**Issue by qw123wh** [OmGodse/Notally#28]
Hello it would be very useful to be able to click links in the notes.  I found this android library that could possibly make your job easier.  Take a look.

https://github.com/klinker24/Android-TextView-LinkBuilder

It is a fundamental function for me and I like your app and I would very much like this function to be implemented.  I no longer know where to look for some useful library

**Comment by OmGodse** [comment]
Clickable links are under progress right now. They'll be added in the next update.

**Comment by qw123wh** [comment]
Thank you look forward to the next update.  
Look at this open source library  https://github.com/beworker/edge-to-edge   could you add it to do this?
![C4560467-FF7C-4CCD-8A20-24ABE096B6EA](https://user-images.githubusercontent.com/59417474/90330484-42b95580-dfad-11ea-9bf5-8e15c8894f8b.jpeg)
![4FE7FB76-D937-46A2-A68D-84AAE46A1FD5](https://user-images.githubusercontent.com/59417474/90330486-44831900-dfad-11ea-8840-77465235bf29.jpeg)

**Comment by OmGodse** [comment]
Added clickable links. You can either wait for it to roll out on the Play Store (Rate it if you want to there) or get it [here](https://github.com/OmGodse/Notally/releases/tag/v2.9)

**Comment by qw123wh** [comment]
I updated with github version 2.9 and nothing has changed, the links are not clicking.  I'll wait for the Playstore version and let you know

**Comment by OmGodse** [comment]
You have to actually long press on the text and mark it as a link

**Comment by qw123wh** [comment]
ok, I did it even if it's not so intuitive.  Specify it better in the description.  Thank you
