### ISSUE TITLE
Not Every Option Initially Appears When Opening a Submenu in Landscape mode

### ISSUE THREAD

**Issue by moriel5** [OmGodse/Notally#29]
This is only a real issue when there are only two option (such as Make List and Take Note), however as the title suggests, not every option initially appears in landscape mode when opening a submenu), necessitating a swipe to pull the other options into view.

My suggestion is to try doing something similiar to what TrackerCheckerMobile does (minus the shade), and instead of pulling an entire pane for something like creating notes, just add another button, with labels next to them.

Enclosed is the influence for my suggestion.

![Screenshot_20200809-070640](https://user-images.githubusercontent.com/20175297/89747848-36269000-dac9-11ea-890e-408b9a9748c7.png)

**Comment by OmGodse** [comment]
Look, even if I use an expandable menu like the one you attached a picture of above, that's not the only place where there are only 2 options. You have labels, deleted and archived pages too. 

I don't think this is a bug at all. All you have to do to access the options is scroll up a little on the bottom sheet.

**Comment by moriel5** [comment]
Accepted. I guess we simply have different ideas for this.

I was thinking about having things closer to where the finger already is (like how Android 7 brought menus to where the button was pressed).
