### ISSUE TITLE
Scroll to hide toolbar

### ISSUE THREAD

**Issue by sojusnik** [OmGodse/Notally#31]
Especially when using your app in horizontal mode while writing longer texts, it would be very helpful, if the toolbar could be automatically hidden when scrolling down or the text goes over the screen. Scrolling up should bring the toolbar back. For a live example see f.i. [Pure Writer](https://play.google.com/store/apps/details?id=com.drakeet.purewriter).

Thus, we would get more vertical space and make the screen more minimalistic, read elegant, without sacrificing functionality.

**Comment by OmGodse** [comment]
The toolbar used to hide on scrolling before, but I've removed that behavior. Unlike Pure Writer, Notally wasn't created for writing long form notes, it's more suitable for everyday use. Thus, keeping the options accessible and fixed at the top is a greater priority than freeing up vertical space.
