### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by sojusnik** [OmGodse/Notally#32]
When using your app in connection with a Bluetooth keyboard, I tend to place my phone further away making it hard to read the text. An option to increase the font size of the text would really help.

**Comment by OmGodse** [comment]
I'm afraid that's not going to happen. It would require a very large and unnecessary amount of effort to fight the system everywhere text is displayed in the app and replace it with a custom method.

Moreover, there's already a way to increase the font size of the text. Just go to your device settings > Display > Font Size (The exact location might differ depending on what version of Android you're on)

**Comment by sojusnik** [comment]
I'm speaking not about the UI text size of Notally, but only the text size when writing a note. Nearly every text editor app has such an option, imho, your app will benefit from it too.

**Comment by OmGodse** [comment]
You can simply increase your device font size when writing a note with a Bluetooth keyboard and decrease it later

**Comment by sojusnik** [comment]
Even on the largest device font setting the text in the edit view looks too small for my use case.

**Comment by OmGodse** [comment]
Have you tried keeping your device closer?

**Comment by sojusnik** [comment]
The idea behind the customizable text size in the edit view is to use your app in connection with a Bluetooth keyboard as a kind of typewriter, at least one arm length away. So, no, keeping the device closer won't help here.
