### ISSUE TITLE
Add URL when sharing text selection to Notally

### ISSUE THREAD

**Issue by sojusnik** [OmGodse/Notally#36]
When sharing a text selection from Firefox, only the title of the webpage and the selected text is saved, but not the URL.

Is it possible to also add the URL when sharing a text to Notally?

**Comment by OmGodse** [comment]
Could you perhaps send a video elaborating what you mean by that?

**Comment by qw123wh** [comment]
Thank you look forward to the next update.  
Look at this open source library https://github.com/beworker/edge-to-edge   could you add it to do this?

![8DE1BE8A-7AE4-4DFE-A908-F03D9FA24F65](https://user-images.githubusercontent.com/59417474/90330445-00901400-dfad-11ea-99dc-58b2e9e9f874.jpeg)
![754E258A-906A-4A8D-8D8D-A570FD5C0CC0](https://user-images.githubusercontent.com/59417474/90330446-0259d780-dfad-11ea-9226-491af7276a1c.jpeg)

**Comment by sojusnik** [comment]
See first picture for sharing from Firefox and second for Pocket. The first one is missing the proper title of the website and the URL, while the latter does it correctly.

**Firefox**
![share with firefox](https://user-images.githubusercontent.com/1245718/92980151-587b4700-f495-11ea-976f-b0773180eb9c.png)

**Pocket**
![share with pocket](https://user-images.githubusercontent.com/1245718/92980170-65983600-f495-11ea-9a5a-fe3e5b8d44a9.png)

**Comment by OmGodse** [comment]
When you share something, the application launches and intent and supplies it with various fields, which the recieving application can read.

Notally uses the constants `EXTRA_SUBJECT` and `EXTRA_TEXT` for the title and body respectively. This is consistent with other apps such as Gmail, Keep, Samsung Notes, etc. 

It seems Firefox does not use the proper fields to pass on the URL whereas Pocket does. This, I'm afraid that's not in my hand.
