### ISSUE TITLE
[Feature Request] Add picture, voice and background support.

### ISSUE THREAD

**Issue by Oymate** [OmGodse/Notally#37]
Also awesome app!

**Comment by OmGodse** [comment]
Could you elaborate a little on what exactly are you looking for?

**Comment by Oymate** [comment]
Yes, 
1. Option to add pictures in notes.
2. Option to record and add voice file(mp3, ogg, flac)
3. Add wallpaper like miui notes

**Comment by OmGodse** [comment]
I'm sorry but Notally's purpose is to be a clean and simple **textual** note taking app. Adding pictures and voice recordings is not part of the scope, there are many feature rich apps which offer that e.g. Google Keep. Wallpapers will also not be supported as colorful notes are planned for the future and both will conflict with each other.
