### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by qw123wh** [OmGodse/Notally#4]
hello I really like your app, but two very useful things are missing.
1 add the possibility that the notes are saved even if you close the app, for example I am writing an important note for some strange case I restart the phone automatically, or I accidentally close the app in the background or I am writing an important note and  the phone is switched off due to a low battery.  
2 add the ability to click on the links, in fact if in my notes I put a link for example an amazon link and after a while I want to access that link I have to copy and paste it on the browser and find it uncomfortable.

**Comment by OmGodse** [comment]
Glad to hear you like the app! 
Makings links clickable and editable at the same time is a bit difficult, so I'm afraid that will have to wait for a while.
Regarding your 1st request, auto save functionality has been added in the latest commit. Grab the APK from the releases page or update the app from Google Play when you see an option,

**Comment by qw123wh** [comment]
Thanks the new version 1.8 works perfectly.


As for the links I don't know if it can help you try looking at these 2 apps for the notes that have this function.

https://github.com/BijoySingh/Scarlet-Notes


https://github.com/CarnetApp/CarnetFdroid


Try to see if you can implement this function by taking what you need for the link from these 2 apps

**Comment by qw123wh** [comment]
I close here and reopen in #28
