### ISSUE TITLE
[feature request] Store notes in markdown format

### ISSUE THREAD

**Issue by Surendrajat** [OmGodse/Notally#40]
Relates to #8. When you decide to store notes in a dir for sync...
Could you please add support for export/backup/store notes in markdown format instead of some custom xml/html format? Also if possible one file per note?

I write all my notes in markdown on PC and keep them in sync with my phone. Currently I have to use some markdown editor to edit those. It will be very useful if Notally supports .md files directly (It's fine if not all features are supported in editor).

**Comment by mmBesar** [comment]
> Relates to #8. When you decide to store notes in a dir for sync...
> Could you please add support for export/backup/store notes in markdown format instead of some custom xml/html format? Also if possible one file per note?
> 
> I write all my notes in markdown on PC and keep them in sync with my phone. Currently I have to use some markdown editor to edit those. It will be very useful if Notally supports .md files directly (It's fine if not all features are supported in editor).

+1 for this

**Comment by femto-code** [comment]
> Relates to #8. When you decide to store notes in a dir for sync...
> Could you please add support for export/backup/store notes in markdown format instead of some custom xml/html format? Also if possible one file per note?
> 
> I write all my notes in markdown on PC and keep them in sync with my phone. Currently I have to use some markdown editor to edit those. It will be very useful if Notally supports .md files directly (It's fine if not all features are supported in editor).

another +1 for this
Really important feature for making sync possible...

**Comment by OmGodse** [comment]
I wasn't aware of Markdown when I added rich text editing functionality to the app. So, I opted for a custom XML format that unfortunately is not inter compatible with Markdown.

Thus, even if sync does become possible, Markdown won't be supported.
