### ISSUE TITLE
[Request] Make the navbar the same color as the rest of the app

### ISSUE THREAD

**Issue by Salt505** [OmGodse/Notally#47]
As you can see in the attached screenshot, the navbar is a deep black and doesn't match the rest of the color of the app. It would look nicer if the navbar matched the color of the app. Thanks :) 
![Screenshot_20201218-150859](https://user-images.githubusercontent.com/44946401/102629505-2a1ba080-4143-11eb-9d0a-cb8165368b7d.png)

**Comment by OmGodse** [comment]
Making the navigation bar black instead of the color of the background was an intentional decision, to allow it to stand out.
