### ISSUE TITLE
Put unticked items on top

### ISSUE THREAD

**Issue by gprst** [OmGodse/Notally#54]
Hi ! Thank you very much for your app. It looks gorgeous, does what it does well, and seems very promising 👏

Now, about my feature request : could it be possible to sort ticked and unticked items (in a list note of course) to put unticked ones on top ?

**Comment by OmGodse** [comment]
You're welcome :)

Although it is possible in theory, in practice it would be very complicated. I also don't think that it's the correct way for ordering, a simple list is far better.

**Comment by gprst** [comment]
@OmGodse I was thinking about a behavior you can find on SimpleNotes, and Google Keep, which actually is : put ticked items at the bottom (rather than unticked ones on top). Wouldn't it be easier to implement ?

**Comment by OmGodse** [comment]
Not really. Right now we just present the items as a simple list and leave the sorting to the user. It can be done but I personally don't think that it's required.
